name: Node.js CI

on:
  repository_dispatch:
  schedule:
    - cron: '5 12 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest

POST https://api.github.com/repos/iambollareddy/Demo/dispatches 
Authorization: Bearer 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

{"event_type":"hello"}

curl --request POST \
 --url 'https://api.github.com/repos/iambollareddy/Demo/dispatches' \
  --header 'authorization: Bearer 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' \
  --data '{"event_type": "hello"}'
